first/first/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    # path('project01', include('project01/diary.urls')),
]

first/project02/project02/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee.urls')),
]

first/project04/project4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # 増えた
from django.conf.urls.static import static  # 増えた

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('videos.urls')),
]

# 開発環境時のみ、Djangoアプリケーション側でメディアファイルを配信する
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

first/project04/videos/urls.py
from django.urls import path
from . import views

app_name = 'videos'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('upload/', views.CreateView.as_view(), name='upload'),
    path('play/<int:pk>/', views.PlayView.as_view(), name='play'),
]

first/project04/videos/models.py
from django.db import models


class Video(models.Model):
    """動画"""

    title = models.CharField('Video Title', max_length=255)
    description = models.TextField('Descriptions(optional)', blank=True)
    thumbnail = models.ImageField('Thumbnail(optional)', upload_to='thumbnails/', null=True, blank=True)  # /media/thumbnails/ファイル名
    upload = models.FileField('File', upload_to='uploads/%Y/%m/%d/')  # /media/uploads/2018/3/20/ファイル名
    created_at = models.DateTimeField('Created date', auto_now_add=True)  # default=timezone.nowと違い、入力欄は表示されない
    updated_at = models.DateTimeField('Update date', auto_now=True)  # 更新するたびにその日時が格納される

    def __str__(self):
        return self.title

first/project04/videos/forms.py
from django import forms
from .models import Video


class VideoCreateForm(forms.ModelForm):

    class Meta:
        model = Video
        fields = ('title', 'description', 'thumbnail', 'upload')
        # 少しツウな書き方
        widgets = {
            'title': forms.TextInput(attrs={  # <input type="text" class="form-control"
                'class': 'form-control',
            }),
            'description': forms.Textarea(attrs={  # <textarea class="form-cotrol"
                'class': 'form-control',
            }),
            'thumbnail': forms.ClearableFileInput(attrs={  # <input type="file" class="form-control-file"
                'class': "form-control-file",
            }),
            'upload': forms.ClearableFileInput(attrs={
                'class': "form-control-file",
            }),
        }

first/project04/videos/views.py
from django.urls import reverse_lazy
from django.views import generic
from .forms import VideoCreateForm
from .models import Video


class IndexView(generic.ListView):
    model = Video


class CreateView(generic.CreateView):
    model = Video
    form_class = VideoCreateForm
    success_url = reverse_lazy('videos:index')


class PlayView(generic.DetailView):
    model = Video

first/project04/videos/templates/videos/base.html
{% load static %}
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    
    <!-- my css -->
    <link rel="stylesheet" href="{% static 'videos/main.css' %}">

    <title>SimpleTube</title>
  </head>
  <body>
    <!-- 上部メニュー -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'videos:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'videos:upload' %}">Upload</a>
          </li>
        </ul>
      </div>
    </nav><!-- 上部メニュー終わり -->

    <div class="container">
      <div class="jumbotron">
        <h1 class="display-3">SimpleTube</h1>
        <p class="lead">Simple Video Upload Page.</p>
        <hr class="my-2">
      </div>
      {% block content %}{% endblock %}
    </div>
  
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
  </body>
</html>

first/project04/videos/templates/videos/video_detail.html
{% extends 'videos/base.html' %}
{% block content %}
<h1>{{ video.title }}</h1>
<p>{{ video.description }}</p>
<p class="text-muted">Upload date: {{ video.created_at }} - Update date: {{ video.updated_at }}</p>
<div class="embed-responsive embed-responsive-16by9">
  <video controls class="embed-responsive-item" src="{{ video.upload.url }}"></video>
</div>
{% endblock %}

first/project04/videos/templates/videos/video_form.html
{% extends 'videos/base.html' %}
{% block content %}
<form action="" method="POST" enctype='multipart/form-data'>
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-dark">Submit</button>
</form>

{% endblock %}

first/project04/videos/templates/videos/video_list.html
{% extends 'videos/base.html' %}
{% load static %}
{% block content %}
<div class="row">
  {% for video in video_list %}
    <div class="col-6 col-md-2">
      <a href="{% url 'videos:play' video.pk %}">
        {% if video.thumbnail %}
          <img class="img-thumbnail" src="{{ video.thumbnail.url }}" alt="{{ video.title }}">
        {% else %}
          <img class="img-thumbnail" src="{% static 'videos/noimage.jpg' %}" alt="{{ video.title }}">
        {% endif %}
      </a>
      <p class="text-center">{{ video.title }}</p>
    </div>
  {% endfor %}
</div>
{% endblock %}