first/first/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    # path('project01', include('project01/diary.urls')),
]

first/project02/project02/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee.urls')),
]

first/project03/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('category/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('comment/<int:post_pk>', views.CommentView.as_view(), name='comment'),
]

first/project04/project4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # 増えた
from django.conf.urls.static import static  # 増えた

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('videos.urls')),
]

# 開発環境時のみ、Djangoアプリケーション側でメディアファイルを配信する
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

first/project03/blog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Category(models.Model):
    # Blog category
    name = models.CharField('category_name', max_length=255)
    created_at = models.DateTimeField('created_date', default=timezone.now)

    def __str__(self):
        return self.name
    
class Post(models.Model):
    # Blog content
    title = models.CharField('title', max_length=255)
    text = models.TextField('content')
    created_at = models.DateTimeField('created_date', default=timezone.now)
    category = models.ForeignKey(Category, verbose_name='category', on_delete=models.PROTECT)

    def __str__(self):
        return self.title
    
class Comment(models.Model):
    # Blog comment
    name = models.CharField('name', max_length=30, default='nemo')
    text = models.TextField('text')
    post = models.ForeignKey(Post, verbose_name='linkedcontent', on_delete=models.PROTECT)
    created_at = models.DateTimeField('created_date', default=timezone.now)

    def __str__(self):
        return self.text[:10]
    

first/project03/blog/forms.py
from django import forms
from .models import Comment

class CommentCreateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Comment
        fields = ('name', 'text')

first/project03/blog/views.py
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from .forms import CommentCreateForm
from .models import Post, Category, Comment



# Create your views here.
class IndexView(generic.ListView):
    # template_name = 'blog/post_list.html'
    model = Post
    paginate_by = 2

    def get_queryset(self):
        queryset = Post.objects.order_by('-created_at')
        keyword = self.request.GET.get('search-key')
        if keyword:
            queryset = queryset.filter(
                Q(title__icontains=keyword) | Q(text__icontains=keyword)
            )
        return queryset

class CategoryView(generic.ListView):
    model = Post
    paginate_by = 2

    def get_queryset(self):
        category = get_object_or_404(Category, pk=self.kwargs['pk'])
        queryset = Post.objects.order_by('-created_at').filter(category=category)
        return queryset

class DetailView(generic.DetailView):
    model = Post

class CommentView(generic.CreateView):
    model = Comment
    form_class = CommentCreateForm

    def form_valid(self, form):
        post_pk = self.kwargs['post_pk']
        comment = form.save(commit=False)
        comment.post = get_object_or_404(Post, pk=post_pk)
        comment.save()
        return redirect('blog:detail', pk=post_pk)

first/project03/blog/templates/blog/base.html
<!doctype html>
<html lang="ja">
  <head>
    <title>Blog</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    {% block extracss %}{% endblock extracss %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Blog</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'blog:index' %}">Home</a>
          </li>
          {% if user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'blog:index' %}">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name='search-key'>
          <button class="btn btn-outline-success .my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
      <div class="jumbotron">
        <h1 class="display-3">Welcome my blog.</h1>
        <p class="lead">This page is our blog.</p>
        <hr class="my-2">
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-8">
            {% block content %}
            {% endblock content %}
          </div>
          <div class="col-md-4">
            <ul class="list-group">
              <li class="list-group-item bg-dark text-white">Category list</li>
              {% for category in category_list %}
                <li class="list-group-item"><a href="{% url 'blog:category' category.pk %}">{{ category }}</a></li>
              {% endfor %}
            </ul>  
          </div>
        </div>
      </div>
      <footer class="bg-dark text-white text-center py-3">
        <p>Your name.</p>
      </footer>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    {% block extrajs %}{% endblock extrajs %}

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
  </body>
</html>

first/project03/blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}

{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
            {{ field }}
            {{ field.errors }}
        </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-dark">Submit</button>
</form>
{% endblock content %}

first/project03/blog/templates/blog/page.html
{% load mytag %}
<nav aria-label="Page navigation">
  <ul class="pagination">
 
      {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}
    
      {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
    
      {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    
  </ul>
</nav>

first/project03/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="card mb-3">
    <h2 class="card-header bg-dark text-white">{{ post.title }}</h2>
    <div class="card-body">
        <p>{{ post.created_at }}, {{ post.category }}</p>
        {{ post.text | linebreaksbr | urlize }}
    </div>
</div>

{% for comment in post.comment_set.all %}
<p>
    {{ comment.name}}<br>
    {{ comment.text | linebreaksbr }}
</p>
{% endfor %}

<a class="btn btn-dark" href="{% url 'blog:comment' post.pk %}">Enter comment</a>
{% endblock content %}

first/project03/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
{% for post in post_list %}
    <div class="card mb-3">
        <h2 class="card-header bg-dark text-white">{{ post.title }}</h2>
        <div class="card-body">
            <p>{{ post.created_at }}, {{ post.category }}</p>
        <a href="{% url 'blog:detail' post.pk %}" class="btn btn-dark">Read more</a>
        </div>
    </div>  
{% endfor %}

{% include 'blog/page.html' %}

{% endblock content %}