first/first/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    # path('project01', include('project01/diary.urls')),
]

first/func_sample/diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('update/<int:pk>', views.update, name='update'),
    path('delete/<int:pk>', views.delete, name='delete'),
    path('detail/<int:pk>', views.detail, name='detail'),
]

first/project01/diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('add/', views.AddView.as_view(), name='add'),
    path('update/<int:pk>', views.UpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.DeleteView.as_view(), name='delete'),
    path('detail/<int:pk>', views.DetailView.as_view(), name='detail'),
]

first/project04/project4/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # 増えた
from django.conf.urls.static import static  # 増えた

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('videos.urls')),
]

# 開発環境時のみ、Djangoアプリケーション側でメディアファイルを配信する
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

first/func_sample/diary/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Day(models.Model):
    title = models.CharField('Title', max_length=200)
    text = models.TextField('Text')
    date = models.DateTimeField('DATE', default=timezone.now)

first/project01/diary/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Day(models.Model):
    title = models.CharField('Title', max_length=200)
    text = models.TextField('Text')
    date = models.DateTimeField('DATE', default=timezone.now)

    def __str__(self):
        return self.title
    

first/func_sample/diary/forms.py
from django import forms
from .models import Day

class DayCreateForm(forms.ModelForm):

    class Meta:
        model = Day
        fields = '__all__' # ('title', 'text', 'date') 

first/func_sample/diary/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import DayCreateForm
from .models import Day

# Create your views here.
def index(request):
    context = {
        'day_list': Day.objects.all()
    }
    return render(request, 'diary/day_list.html', context)

def add(request):
    form = DayCreateForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('diary:index')

    context = {
        'form': form
    }
    return render(request, 'diary/day_form.html', context)

def update(request, pk):
    day = get_object_or_404(Day, pk=pk)

    form = DayCreateForm(request.POST or None, instance=day)

    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('diary:index')

    context = {
        'form': form
    }
    return render(request, 'diary/day_form.html', context)

def delete(request, pk):
    day = get_object_or_404(Day, pk=pk)

    if request.method == 'POST':
        day.delete()
        return redirect('diary:index')

    context = {
        'day': day
    }
    return render(request, 'diary/day_confirm_delete.html', context)

def detail(request, pk):
    day = get_object_or_404(Day, pk=pk)

    context = {
        'day': day
    }
    return render(request, 'diary/day_detail.html', context)

first/project01/diary/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic
from .forms import DayCreateForm
from .models import Day
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
# def index(request):
#     context = {
#         'day_list': Day.objects.all()
#     }
#     return render(request, 'diary/day_list.html', context)

# def add(request):
#     form = DayCreateForm(request.POST or None)

#     if request.method == 'POST' and form.is_valid():
#         form.save()
#         return redirect('diary:index')

#     context = {
#         'form': form
#     }
#     return render(request, 'diary/day_form.html', context)

# def update(request, pk):
#     day = get_object_or_404(Day, pk=pk)

#     form = DayCreateForm(request.POST or None, instance=day)

#     if request.method == 'POST' and form.is_valid():
#         form.save()
#         return redirect('diary:index')

#     context = {
#         'form': form
#     }
#     return render(request, 'diary/day_form.html', context)

# def delete(request, pk):
#     day = get_object_or_404(Day, pk=pk)

#     if request.method == 'POST':
#         day.delete()
#         return redirect('diary:index')

#     context = {
#         'day': day
#     }
#     return render(request, 'diary/day_confirm_delete.html', context)

# def detail(request, pk):
#     day = get_object_or_404(Day, pk=pk)

#     context = {
#         'day': day
#     }
#     return render(request, 'diary/day_detail.html', context)

class IndexView(generic.ListView):
    model = Day
    paginate_by = 3

class AddView(LoginRequiredMixin, generic.CreateView):
    model = Day
    form_class = DayCreateForm
    success_url = reverse_lazy('diary:index')

class UpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Day
    form_class = DayCreateForm
    success_url = reverse_lazy('diary:index')

class DeleteView(LoginRequiredMixin, generic.DeleteView):
    model= Day
    success_url = reverse_lazy('diary:index')

class DetailView(generic.DetailView):
    model = Day

first/project01/diary/templates/diary/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    {% block extracss %}{% endblock extracss %}

    <title>Diary App</title>
  </head>
  <body>
      <div class="container">
        <nav class="nav">
            <a class="nav-link" href="{% url 'diary:index' %}">List</a>
            {% if user.is_superuser %}
              <a class="nav-link" href="{% url 'diary:add' %}" target="_blank">Add</a>
            {% endif %}
        </nav>
        {% block content %}
        {% endblock content %}
      </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    {% block extrajs %}{% endblock extrajs %}

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
  </body>
</html>

first/project01/diary/templates/diary/day_delete.html
{% extends 'diary/base.html' %}

{% block content %}
<table class="table">
    <tr>
        <th>Title</th>
        <td>{{ day.title }}</td>
    </tr>
    <tr>
        <th>Text</th>
        <td>{{ dayda.text }}</td>
    </tr>
    <tr>
        <th>Date</th>
        <td>{{ day.date }}</td>
    </tr>
</table>
{% endblock content %}

first/project01/diary/templates/diary/day_form.html
{% extends 'diary/base.html' %}

{% block content %}
<p>{{ day.tilte }}</p>
<form action="" method="POST">
    <table class="table">
        <tr>
            <th>{{ form.title.label }}</th>
            <td>{{ form.title }}</td>
        </tr>
        <tr>
            <th>{{ form.text.label }}</th>
            <td>{{ form.text }}</td>
        </tr>
        <tr>
            <th>{{ form.date.label }}</th>
            <td>{{ form.date }}</td>
        </tr>
    </table>
    <button type="submit" class="btn btn-primary">Submit</button>
    {% csrf_token %}
</form>
{% endblock content %}

first/project01/diary/templates/diary/day_list.html
{% extends 'diary/base.html' %}

{% block content %}
<h1>Day list</h1>
<table class="table">
    <thead>
        <tr>
            <th>TITLE</th>
            <th>DATE</th>
            <th>#</th>
            <th>#</th>
        </tr>
    </thead>
    <tbody>
        {% for day in day_list %}
        <tr>
            <td><a href="{% url 'diary:detail' day.pk %}">{{ day.title }}</a></td>
            <td>{{ day.date }}</td>
            <td>
                {% if user.is_superuser %}
                    <a href="{% url 'diary:update' day.pk %}" target="_blank">Update</a>
                {% endif %}
            </td>
            <td>
                {% if user.is_superuser %}
                    <a href="{% url 'diary:delete' day.pk %}" target="_blank">Delete</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% include 'diary/page4.html' %}

{% endblock content %}

first/project01/diary/templates/diary/page1.html
{% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
{% endif %}

{% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">Next</a>
{% endif %}

first/project01/diary/templates/diary/page2.html
{% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
{% endif %}

{% for num in page_obj.paginator.page_range %}
     {% if page_obj.number == num %}
          <span>{{ num }}</span>
     {% else %}
          <a href="?page={{ num }}">{{ num }}</a>
     {% endif %}
{% endfor %}

{% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">Next</a>
{% endif %}

first/project01/diary/templates/diary/page3.html
{% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
{% endif %}

Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages}}

{% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">Next</a>
{% endif %}